### PR TITLE
Refactored codebase

### PR DESCRIPTION
**Pull request by arjunvuppala123**
the response to issue #49

### CODE REVIEW

**Review by srujandeshpande — CHANGES_REQUESTED** [review]
Can you rename `href` folder to `events`? More descriptive

**Comment by arjunvuppala123** [comment]
done it has been renamed

**Review by srujandeshpande — CHANGES_REQUESTED** [review]
Couple more minor things:
1. Hacktoberfest 2020 Image not showing
2. Tensor Image not showing
3. Hacktoberfest 2019 has the 2020 teaser image
Screenshot from 2021-01-07 17-21-08
Screenshot from 2021-01-07 17-21-30
Screenshot from 2021-01-07 17-21-39

**Review by srujandeshpande — APPROVED** [review]
LGTM!

**Pull request merged**
